// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/prince-bansal/go-otp/config"
	"github.com/prince-bansal/go-otp/internal/features/apiKey"
	"github.com/prince-bansal/go-otp/internal/features/health"
	"github.com/prince-bansal/go-otp/internal/features/organisation"
	"github.com/prince-bansal/go-otp/internal/routes"
)

// Injectors from di.go:

func InitDependencies() *config.AppConfig {
	organisationService := organisation.NewOrganisationService()
	organisationHandler := organisation.NewOrganisationHandler(organisationService)
	healthHandler := health.NewHealthHandler()
	apiService := apiKey.NewApiService()
	apiKeyHandler := apiKey.NewApiHandler(apiService)
	router := routes.NewRouter(organisationHandler, healthHandler, apiKeyHandler)
	appConfig := config.NewAppConfig(router)
	return appConfig
}
